### ISSUE TITLE
[BUG]: InternalValidate error in github_actions_secret resource (v6.7.2)

### ISSUE THREAD

**Issue by joshuamkite-nfb** [integrations/terraform-provider-github#2839]
### Expected Behavior

Provider should initialize successfully and allow terraform plan/apply operations with github_actions_secret resources.

### Actual Behavior

Provider fails during initialization with an InternalValidate error:

Error: InternalValidate
  with provider["registry.terraform.io/integrations/github"],
  on provider.tf line 2, in provider "github":
   2: provider "github" {

Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

resource github_actions_secret: No Update defined, must set ForceNew on:
[]string{"destroy_on_drift"}

### Terraform Version

Terraform v1.8.2
on linux_amd64
+ provider registry.terraform.io/integrations/github v6.7.2

### Affected Resource(s)

- github_actions_secret

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

resource "github_actions_secret" "this" {
  for_each        = var.secrets
  repository      = github_repository.this.name
  secret_name     = each.key
  encrypted_value = each.value
}
```

### Steps to Reproduce

1. Use GitHub provider version 6.7.2
2. Define a github_actions_secret resource in your configuration
3. Run terraform init
4. Run terraform plan

### Debug Output

```shell
Pin to version 6.7.1 or earlier:

version = "~> 6.7.0, < 6.7.2"
```

### Panic Output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by GerardSoleCa** [comment]
I'm experiencing the same issue.

**Comment by srgustafson8** [comment]
Duplicate of #2838 I believe

**Comment by ypodo** [comment]
also here
│ Error: InternalValidate
│ 
│   with provider["registry.terraform.io/hashicorp/github"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ Internal validation of the provider failed! This is always a bug
│ with the provider itself, and not a user issue. Please report
│ this bug:
│ 
│ resource github_actions_secret: No Update defined, must set ForceNew on:
│ []string{"destroy_on_drift"}
╵
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/hashicorp/github" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.

**Comment by fivesheep** [comment]
please revoke this version from terraform provider registry. it's impacting everyone

**Comment by srgustafson8** [comment]
@nickfloyd as the releaser of 6.7.3 - are you able to address this? thank you

**Comment by armyofda12mnkeys** [comment]
Was this fixed? i noticed our Terraform's were failing yesterday in the morning/afternoon, but suddenly later in the afternoon (like 5-6pm EST) yesterday they were working again without me updating the github provider settings for Terraform.

**Comment by nickfloyd** [comment]
> please revoke this version from terraform provider registry. it's impacting everyone

@fivesheep So our policy and what the Terraform repository suggests is that we roll forward.  If we delete tags or submit a request to revoke a release it can cause issues.  Apologies for the trouble I know that can be frustrating.  We're doing our best to get things stabilized and definitely appreciate the paitence.

**Comment by nickfloyd** [comment]
This issue should be fixed with v6.7.3

**Comment by zepeng811** [comment]
@nickfloyd I'm still seeing similar issue in `v6.7.4`, but with slightly different error message than the one posted in the original issue.

```
╷
│ Error: InternalValidate
│ 
│   with provider["registry.terraform.io/integrations/github"],
│   on _init.tf line 33, in provider "github":
│   33: provider "github" {
│ 
│ Internal validation of the provider failed! This is always a bug
│ with the provider itself, and not a user issue. Please report
│ this bug:
│ 
│ resource github_actions_organization_secret: All fields are ForceNew or
│ Computed w/out Optional, Update is superfluous
│ resource github_actions_secret: All fields are ForceNew or Computed w/out
│ Optional, Update is superfluous
╵
```

rolling back to `v6.7.0` fixes the error.

**Comment by eyalgal** [comment]
This issue should be fixed with [v6.7.5](https://github.com/integrations/terraform-provider-github/releases/tag/v6.7.5)

**Comment by joshuamkite-nfb** [comment]
so if there is a new release that addresses this should this not be closed?

**Comment by eyalgal** [comment]
I just wanted to make sure you had a chance to verify that the fix works before closing the issue. I’ll go ahead and close it now.
