### ISSUE TITLE
Only administrators can create internal repositories in organizations that restrict changing repository visibility to administrators

### ISSUE THREAD

**Issue by jtgrohn** [integrations/terraform-provider-github#788]
### Terraform Version
```
0.15.3
```

### Provider Version
```
terraform {
  required_providers {
    github = "4.9.4"
  }
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`

### Terraform Configuration Files
```hcl
resource "github_repository" "test_repo" {
  name = "test_repo"

  visibility    = "internal"
}
```

### Debug Output
```
│ Error: PATCH https://api.github.com/repos/rtkwlf/test_repo: 422 Visibility can't be changed by this user. []
│ 
│   with github_repository.test_repo,
│   on repositories.tf line 31, in resource "github_repository" "test_repo":
│   31: resource "github_repository" "test_repo" {
```

### Expected Behavior
The repository should have been created with `internal` visibility

### Actual Behavior
The repository was created with `private` visibility. Switching it to `internal` visibility failed.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Our GitHub Organization only allows  Administrators to change repository visibility and we want the terraform to be executable by non-administrator users

![image](https://user-images.githubusercontent.com/14808144/118541348-9238d780-b71f-11eb-8385-bf06578dc9f8.png)

### References
- PR [#781] added the ability to create `internal` repositories in GHE organizations, but I suspect was only tested by an administrator or in an organization where non-administrator users can change repository visibility

**Comment by ingledl** [comment]
I'd like to see this corrected as well as our org only allows internal repository creation by its members. Creating a private repo and then switching its visibility will both be blocked with our currently configured settings.

**Comment by ingledl** [comment]
This is resolved with release [4.12.1](https://github.com/integrations/terraform-provider-github/releases/tag/v4.12.1). We have verified it as working in our org. I recommend closing the ticket.

**Comment by dimisjim** [comment]
The problem still persists when trying to change visibility.
